name: Build

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 30
        
    - name: Build summary
      run: |
        echo "## Build Summary 🚀" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Dependencies installed successfully" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Project built successfully" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Build artifacts uploaded" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 Build size: $(du -sh dist/ | cut -f1)" >> $GITHUB_STEP_SUMMARY
