name: PR Preview

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build preview
      run: npm run build
      env:
        NODE_ENV: development
        
    - name: Upload preview artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pr-preview-${{ github.event.number }}
        path: dist/
        retention-days: 7
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Preview Build Complete!
            
            ✅ Your PR has been built successfully!
            
            **Build Details:**
            - **Commit:** ${context.sha.substring(0, 7)}
            - **Build Time:** ${new Date().toISOString()}
            - **Artifacts:** Available for download in the Actions tab
            
            You can download the build artifacts to test your changes locally.`
          })
